UPDATE report
SET status = 'PROCESSING'
WHERE status = 'GENERATING'
  AND deleted = 0;

ALTER TABLE report
  MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT 'Report status: PENDING, PROCESSING, COMPLETED, FAILED, ARCHIVED';

UPDATE file_parse_record
SET status = 'SUCCESS'
WHERE status = 'SUCCEEDED'
  AND deleted = 0;

ALTER TABLE file_parse_record
  MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT 'Parse status: PENDING, RUNNING, SUCCESS, FAILED, CANCELED';
